


class Shelter:

    def __init__(self, SHELTER_NAME,CAPACITY,PROGRAM_NAME,ORGANIZATION_NAME,SECTOR,FACILITY_NAME,OCCUPANCY,OCCUPANCY_DATE,SHELTER_PROVINCE,SHELTER_CITY,SHELTER_ADDRESS,SHELTER_POSTAL_CODE):
        self.SHELTER_NAME = SHELTER_NAME
        self.CAPACITY = CAPACITY
        self.PROGRAM_NAME = PROGRAM_NAME
        self.ORGANIZATION_NAME = ORGANIZATION_NAME
        self.SECTOR = SECTOR
        self.FACILITY_NAME = FACILITY_NAME
        self.OCCUPANCY = OCCUPANCY
        self.OCCUPANCY_DATE = OCCUPANCY_DATE
        self.SHELTER_PROVINCE = SHELTER_PROVINCE
        self.SHELTER_CITY = SHELTER_CITY
        self.SHELTER_ADDRESS = SHELTER_ADDRESS
        self.SHELTER_POSTAL_CODE = SHELTER_POSTAL_CODE
